### ISSUE TITLE
Meet The Team Page - Create Team Member Carousel

### ISSUE THREAD

**Issue by rishyendra333** [HackNC/fall2024#7]
Create a carousel component for this page that has a left and right button or arrow to scroll through and see all the team members.  Each tile in the carousel should have an image followed by the name and role underneath them (feel free to get creative with this).

Here is a youtube tutorial that could help with this, but feel free to use a different tutorial if you would like. 
https://www.youtube.com/watch?v=9HcxHDS2w1s 

NOTE: You don't need to add any actual information to the tiles, just format them.

Requirements:
The carousel is visible with tiles and scrollable through some form of a button or an arrow, and each tile has space for an image, name, and role.

**Comment by aryasalian** [comment]
I would suggest having separate carousels for each department(e.g. Dev, Sponsorship and so on) so that the carousel doesn't get too big and clumped up. 

Second suggestion: maybe make the co-leaders, directors and junior directors a separate combined carousel on the top followed by team member carousels for each team one below the other on the webpage. It'd be better if we follow a format similar to most hackathon websites when it comes to implementing things that have already been standardized throughout MLH.

**Comment by vvkash** [comment]
Added Sliders for Directors, Junior Members and Members along with functionaly for arrow buttons and placeholders for images and member info. Let me know if theres anything that needs to be changed or updated!
<img width="1447" alt="Screenshot 2024-06-25 at 8 06 01 PM" src="https://github.com/HackNC/fall2024/assets/121144051/39c7082f-9598-443d-b97f-3b2db99fe4d7">
